version: '3'
services:
  natpoked:
    image: kenvix/natpoked
    container_name: natpoked
    restart: unless-stopped
    volumes:
      - /home/config/natpoked:/data/Config
    environment:
      - DebugMode=true
      - DebugNetworkTraffic=true
      - PeerId=2000001
      - PeerFile=peers.yml
      - PeerMyKey=dTBY2CcC83Az5J
      - AppMode=broker
      - BrokerUrl=
      - BrokerMqttUrl=
      - PortGuessMaxConcurrentNum=100
      - PortGuessMaxNum=55000
      - ServerHttpHost=0.0.0.0
      - ServerKey=bG5Ryqh8ArJico
      - ServerHttpPort=15700
      - ServerMqttPort=15701
      - EchoServerPortRange=15702-15799
      - TZ=Asia/Shanghai
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    network_mode: host
