FROM debian:11
LABEL maintainer="kenvix <i@kenvix.com>"
LABEL description="NATPoked: A Cross-platform Peer-To-Peer NAT Traversal Toolkit - Official docker image"
LABEL homepage="https://kenvix.com"

COPY ./build/output /data/app
COPY ./cmdline-jvm-docker.txt /data/app/cmdline-jvm-docker.txt

RUN echo "Begin docker image build ..." \
    && apt-get update \
    && apt-get install -y \
    ca-certificates \
    openjdk-17-jre-headless \
    mosquitto \
    wireguard \
    kcptun \
    iproute2 \
    net-tools \
    && echo "Cleaning build cache ..." \
    && (mkdir -p /data/app || true) \
    && (mkdir -p /data/config || true) \
    && cd /data/config \
    && (apt-get clean || true) \
    && (rm -rf /tmp/* || true) \
    && echo "Finishing build ..." \
    && (mv /data/app/*.jar /data/app/app.jar || true) \
    && echo "Dockerfile build success"


WORKDIR /data/config
ENV LANG en_US.UTF-8
ENV IsRunningInDocker true

CMD ["java", "@/data/app/cmdline-jvm-docker.txt", "-jar", "/data/app/app.jar"]