FROM debian:11
LABEL maintainer="kenvix <i@kenvix.com>"
LABEL description="NATPoked: A Cross-platform Peer-To-Peer NAT Traversal Toolkit - Official docker image"
LABEL homepage="https://kenvix.com"

COPY ./build/output /data
COPY ./cmdline-jvm-docker.txt /data/cmdline-jvm-docker.txt

RUN echo "Begin docker image build ..." \
    && apt-get update \
    && apt-get install -y \
    ca-certificates \
    openjdk-17-jre-headless \
    mosquitto \
    wireguard \
    kcptun \
    iproute2 \
    net-tools \
    && echo "Cleaning build cache ..." \
    && (mkdir -p /data || true) \
    && (mkdir -p /data/Config || true) \
    && cd /data/Config \
    && (apt-get clean || true) \
    && (rm -rf /tmp/* || true) \
    && echo "Finishing build ..." \
    && (mv /data/*.jar /data/app.jar || true) \
    && echo "Dockerfile build success"


WORKDIR /data
ENV LANG en_US.UTF-8
ENV IsRunningInDocker true

CMD ["java", "@/data/cmdline-jvm-docker.txt", "-jar", "/data/app.jar"]