FROM debian:11
LABEL maintainer="kenvix <i@kenvix.com>"
LABEL description="NATPoked: A Cross-platform Peer-To-Peer NAT Traversal Toolkit - Official docker image"
LABEL homepage="https://kenvix.com"

COPY ./build/output /data/app

RUN echo "Begin docker image build ..." \
    && apt-get update \
    && apt-get install -y \
    ca-certificates \
    openjdk-17-jre-headless \
    mosquitto \
    wireguard \
    kcptun \
    iproute2 \
    net-tools \
    && echo "Cleaning build cache ..." \
    && cd /data/config \
    && apt-get clean \
    && rm -rf /tmp/* \
    && echo "Finishing build ..." \
    && mv /data/app/*.jar /data/app/app.jar \
    && echo "Dockerfile build success"


WORKDIR /data/config
ENV LANG en_US.UTF-8

CMD ["java", "-jar", "/data/app/app.jar"]