name: Docker - Linux mips64le

on:
  workflow_dispatch:
  push:
    branches:
      - master

concurrency:
  group: linux-mips64le-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: natpoked

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Linux Docker Image
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: submodules-init
        uses: snickerbockers/submodules-init@v4

      - name: Download Universal JAR Artifact
        uses: actions/download-artifact@v3
        with:
          name: app.jar
          path: build/output

      - name: Run Docker Prebuild shell
        run: |
          echo "Prebuild shell"
          ls -al
          mkdir -p ./build/output

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set Up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set Up Cache
        uses: actions/cache@v2
        id: buildx-cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx

      - name: Buildx
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile-RuntimeOnly
          platforms: linux/mips64le
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest-mips64le
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

