# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Universal Jar

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  OUTPUT_NAME: natpoked.jar

concurrency:
  group: universal-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: submodules-init
      uses: snickerbockers/submodules-init@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'

    # Runs a set of commands using the runners shell
    - name: Run Prebuild shell
      run: |
        echo "Prebuild shell"
        ls -al
        chmod +x ./gradlew
        
    - name: Build with Gradle
      uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
      with:
        arguments: shadowJar
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        # Artifact name
        name: app.jar
        # A file, directory or wildcard pattern that describes what to upload
        path: build/output/${{ env.OUTPUT_NAME }}
        # The desired behavior if no files are found using the provided path.

